services:
  # Rails API Service
  - type: web
    name: thelibrarian-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thelibrarian-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled

databases:
  # PostgreSQL Database
  - name: thelibrarian-db
    plan: free
    databaseName: thelibrarian_production
    user: thelibrarian
