---
openapi: 3.0.1
info:
  title: Library Management System API
  version: v1
  description: API for managing library books, borrowings, and users with JWT authentication
  contact:
    name: API Support
    email: support@library.com
paths:
  "/api/v1/auth/sign_up":
    post:
      summary: Register a new user
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: user created
          headers:
            Authorization:
              schema:
                type: string
              description: JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    "$ref": "#/components/schemas/User"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      format: password
                    password_confirmation:
                      type: string
                      format: password
                    role:
                      type: string
                      enum:
                      - member
                      - librarian
                      default: member
                  required:
                  - email
                  - password
                  - password_confirmation
  "/api/v1/auth/sign_in":
    post:
      summary: Sign in
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: signed in successfully
          headers:
            Authorization:
              schema:
                type: string
              description: JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: invalid credentials
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      format: password
                  required:
                  - email
                  - password
  "/api/v1/auth/sign_out":
    delete:
      summary: Sign out
      tags:
      - Authentication
      security:
      - Bearer: []
      responses:
        '200':
          description: signed out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/api/v1/books":
    get:
      summary: List all books
      tags:
      - Books
      security:
      - Bearer: []
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: items
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  books:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Book"
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      per_page:
                        type: integer
                      total_count:
                        type: integer
                      total_pages:
                        type: integer
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    post:
      summary: Create a book
      tags:
      - Books
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Book"
        '403':
          description: forbidden - only librarians can create books
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                book:
                  type: object
                  properties:
                    title:
                      type: string
                    author:
                      type: string
                    genre:
                      type: string
                    isbn:
                      type: string
                    total_copies:
                      type: integer
                  required:
                  - title
                  - author
                  - genre
                  - isbn
                  - total_copies
  "/api/v1/books/{id}":
    parameters:
    - name: id
      in: path
      description: Book ID
      required: true
      schema:
        type: integer
    get:
      summary: Show a book
      tags:
      - Books
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Book"
        '404':
          description: book not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    patch:
      summary: Update a book
      tags:
      - Books
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Book"
        '403':
          description: forbidden - only librarians can update books
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                book:
                  type: object
                  properties:
                    title:
                      type: string
                    author:
                      type: string
                    genre:
                      type: string
                    isbn:
                      type: string
                    total_copies:
                      type: integer
                    available_copies:
                      type: integer
    delete:
      summary: Delete a book
      tags:
      - Books
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: forbidden - only librarians can delete books
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/borrowings":
    get:
      summary: List all borrowings
      tags:
      - Borrowings
      security:
      - Bearer: []
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: items
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      - name: status
        in: query
        required: false
        description: Filter by status (borrowed, returned)
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  borrowings:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Borrowing"
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      per_page:
                        type: integer
                      total_count:
                        type: integer
                      total_pages:
                        type: integer
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    post:
      summary: Borrow a book
      tags:
      - Borrowings
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Borrowing"
        '422':
          description: book not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                borrowing:
                  type: object
                  properties:
                    book_id:
                      type: integer
                  required:
                  - book_id
  "/api/v1/borrowings/overdue":
    get:
      summary: List overdue borrowings
      tags:
      - Borrowings
      security:
      - Bearer: []
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: items
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  borrowings:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Borrowing"
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      per_page:
                        type: integer
                      total_count:
                        type: integer
                      total_pages:
                        type: integer
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/borrowings/{id}":
    parameters:
    - name: id
      in: path
      description: Borrowing ID
      required: true
      schema:
        type: integer
    get:
      summary: Show a borrowing
      tags:
      - Borrowings
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Borrowing"
        '404':
          description: borrowing not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    patch:
      summary: Return a book
      tags:
      - Borrowings
      security:
      - Bearer: []
      parameters:
      - name: action_type
        in: query
        required: true
        description: Action to perform (return)
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Borrowing"
        '403':
          description: forbidden - only librarians can update borrowings
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/dashboard":
    get:
      summary: Get dashboard statistics
      tags:
      - Dashboard
      security:
      - Bearer: []
      description: Returns role-specific dashboard statistics. Librarians see library-wide
        stats, members see their personal stats.
      responses:
        '200':
          description: successful - member dashboard
          content:
            application/json:
              schema:
                type: object
                properties:
                  dashboard:
                    type: object
                    properties:
                      total_books:
                        type: integer
                      total_available_books:
                        type: integer
                      total_borrowed_books:
                        type: integer
                      total_members:
                        type: integer
                      overdue_books:
                        type: integer
                      books_due_today:
                        type: integer
                      members_with_overdue_books:
                        type: integer
                      recent_borrowings:
                        type: array
                      popular_books:
                        type: array
                      overdue_borrowings:
                        type: array
                      active_borrowings_count:
                        type: integer
                      overdue_borrowings_count:
                        type: integer
                      books_due_soon:
                        type: integer
                      borrowed_books:
                        type: array
                      borrowing_history:
                        type: array
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
  "/api/v1/health":
    get:
      summary: Health check
      tags:
      - Health
      description: Returns the health status of the API. No authentication required.
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                    - ok
                  timestamp:
                    type: string
                    format: datetime
                  version:
                    type: string
                required:
                - status
  "/api/v1/users/me":
    get:
      summary: Get current user profile
      tags:
      - Users
      security:
      - Bearer: []
      description: Returns the profile information of the currently authenticated
        user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                        format: email
                      role:
                        type: string
                        enum:
                        - librarian
                        - member
                      created_at:
                        type: string
                        format: datetime
                    required:
                    - id
                    - email
                    - role
                required:
                - user
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
servers:
- url: https://thelibrarian-api.onrender.com
  description: Production server
- url: http://localhost:3000
  description: Development server
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/v1/auth/sign_in
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        role:
          type: string
          enum:
          - member
          - librarian
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        isbn:
          type: string
        total_copies:
          type: integer
        available_copies:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Borrowing:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        book_id:
          type: integer
        borrowed_at:
          type: string
          format: date-time
        due_date:
          type: string
          format: date-time
        returned_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
